version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
    - "8080:8080"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_DEBUG: 'true'
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/config/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - chat-network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
    networks:
      - chat-network

  db:
    image: mysql:5.7.24
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - chat-network

  redis:
    image: redis:alpine3.10
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
      - ./docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

